[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Backend Service
[[services]]
name = "backend"
source = "backend"

[services.build]
buildCommand = "../scripts/railway-build.sh"
startCommand = "npm start"

[services.variables]
NODE_ENV = "production"
PORT = "3001"

# Frontend Service  
[[services]]
name = "frontend"
source = "frontend"

[services.build]
buildCommand = "../scripts/railway-build.sh"
startCommand = "npm run preview -- --host 0.0.0.0 --port $PORT"

[services.variables]
NODE_ENV = "production"
PORT = "3000"
NPM_CONFIG_INCLUDE = "optional"
NPM_CONFIG_OPTIONAL = "false" 