[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Backend Service
[[services]]
name = "backend"
source = "backend"

[services.build]
buildCommand = "npm run build"
startCommand = "npm start"

[services.variables]
NODE_ENV = "production"
PORT = "3001"

# Frontend Service  
[[services]]
name = "frontend"
source = "frontend"

[services.build]
buildCommand = "npm run build"
startCommand = "npm run preview -- --host 0.0.0.0 --port $PORT"

[services.variables]
NODE_ENV = "production"
PORT = "3000" 